name: codecov
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        container: golang:1.15.0
        steps:
            - uses: actions/checkout@master
            - name: Generate coverage report
              run: |
                  go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage.txt
                  flags: unittests
                  fail_ci_if_error: true
